# Generated by Django 4.2.5 on 2023-09-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prilozh_app_lesson_4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisements',
        ),
    ]
